---
# Configuration file for MegaLinter (https://megalinter.io/latest/config-variables/)

ENABLE_LINTERS:
  # - CPP_CPPLINT
  # - CPP_CLANG_FORMAT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  # - GROOVY_NPM_GROOVY_LINT
  # - JAVA_CHECKSTYLE
  # - JAVA_PMD
  # - KOTLIN_DETEKT
  # - KOTLIN_KTLINT
  - MARKDOWN_MARKDOWNLINT
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT

# The listed linters will be run, but if errors are found, they will be considered as non-blocking
DISABLE_ERRORS_LINTERS:
  - CPP_CPPLINT
  - CPP_CLANG_FORMAT

# Configuration for individual linters
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: .editorconfig-checker.json
JAVA_CHECKSTYLE_CONFIG_FILE: .sun_checks.xml
JAVA_PMD_CONFIG_FILE: .java-pmd-ruleset.xml

# Global configuration
APPLY_FIXES: none
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
LINTER_RULES_PATH: .
LOG_LEVEL: INFO
MEGALINTER_FILES_TO_LINT: []
PRINT_ALL_FILES: true
PRINT_ALPACA: false
# NB: Regular expressions should be enclosed in parentheses
SECURED_ENV_VARIABLES:
  - GIT_CREDENTIALS
  - (TECHNICAL_USER_.*)
  - (.*TOKEN.*)
  - (.*USER.*)
SHOW_ELAPSED_TIME: true

# Globally ignored files
FILTER_REGEX_EXCLUDE: |
  (?x)(
      ^3rdparty/ignored-app/.+/
    | ^other/ignored/directory
  )
