---
name: on-pr

on:
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      event: pull_request
      warn-on-failure: false

  build:
    uses: ./.github/workflows/build.yml
    with:
      event: pull_request
      build-type: debug
      unit-tests: true
    secrets: inherit
